springdoc:
  swagger-ui:
    path: /swagger-book-vendor.html
  api-docs:
    path: /v3/api-docs
    version: openapi_3_1
  show-actuator: true


spring:
  datasource:
    url: jdbc:h2:mem:bookapidoc
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
